version: '3.8'

services:
  app:
    build:
      context: . # The current directory where the Dockerfile is located
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/trip-service
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
